### ISSUE TITLE
crossenv was compromised

### ISSUE THREAD

**Issue by ArtskydJ** [mmellado/visitedcountries-backend#1]
https://twitter.com/o_cee/status/892306836199800836

If you have anything sensitive in your environment variables, then they were probably leaked.

**Comment by mmellado** [comment]
Thanks for the heads up. luckily no information handled with crossenv is sensitive, but will still update the project to not use it

**Comment by mmellado** [comment]
crossenv package has been replaced in favor of the originally intended cross-env and env variables have been updated, just in case :)
